export const data = [
  {
    image: "",
    id: 1,
    name: "",
    availaibility: true,
    available_for: "Remote work",
    skill: "UI/UX designer",
  },
  {
    image: "",
    id: 2,
    name: "",
    availaibility: true,
    available_for: "Remote work",
    skill: "Frontend Developer",
  },
  {
    image: "",
    id: 3,
    name: "",
    availaibility: false,
    available_for: "Part-time Work",
    skill: "Mobile developer",
  },
  {
    image: "",
    id: 4,
    name: "",
    availaibility: false,
    available_for: "Full-time Work",
    skill: "Backend Developer",
  },
  {
    image: "",
    id: 5,
    name: "",
    availaibility: true,
    available_for: "Remote work",
    skill: "UI/UX designer",
  },
  {
    image: "",
    id: 6,
    name: "",
    availaibility: false,
    available_for: "Full-time Work",
    skill: "Frontend Developer",
  },
  {
    image: "",
    id: 7,
    name: "",
    availaibility: true,
    available_for: "Full-time Work",
    skill: "Frontend Developer",
  },
  {
    image: "",
    id: 8,
    name: "",
    availaibility: true,
    available_for: "Remote work",
    skill: "Mobile developer",
  },
  {
    image: "",
    id: 9,
    name: "",
    availaibility: true,
    available_for: "Full-time Work",
    skill: "Backend Developer",
  },
  {
    image: "",
    id: 10,
    name: "",
    availaibility: true,
    available_for: "Remote work",
    skill: "Mobile developer",
  },
  {
    image: "",
    id: 11,
    name: "",
    availaibility: true,
    available_for: "Full-time Work",
    skill: "UI/UX designer",
  },
  {
    image: "",
    id: 12,
    name: "",
    availaibility: false,
    available_for: "Remote work",
    skill: "Backend Developer",
  },
];
